// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBNyzBLXp-aYkmTHq3wMD-gBYMC8n_l_g',
    appId: '1:116692744942:web:289037f8d44f04557611ff',
    messagingSenderId: '116692744942',
    projectId: 'ci-cd-app-162a0',
    authDomain: 'ci-cd-app-162a0.firebaseapp.com',
    storageBucket: 'ci-cd-app-162a0.appspot.com',
    measurementId: 'G-51DEYJCPRP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJeyZpFq-FUZgoNFGfLKEf8vppmISKDig',
    appId: '1:116692744942:android:ca0c89e7acaa0ad37611ff',
    messagingSenderId: '116692744942',
    projectId: 'ci-cd-app-162a0',
    storageBucket: 'ci-cd-app-162a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlta3q-VKqTUd3g2XIgszD6nhWbpTm2nQ',
    appId: '1:116692744942:ios:d8c0b504b822ce647611ff',
    messagingSenderId: '116692744942',
    projectId: 'ci-cd-app-162a0',
    storageBucket: 'ci-cd-app-162a0.appspot.com',
    iosBundleId: 'com.example.ci',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlta3q-VKqTUd3g2XIgszD6nhWbpTm2nQ',
    appId: '1:116692744942:ios:70227feb4763f95b7611ff',
    messagingSenderId: '116692744942',
    projectId: 'ci-cd-app-162a0',
    storageBucket: 'ci-cd-app-162a0.appspot.com',
    iosBundleId: 'com.example.ci.RunnerTests',
  );
}
