default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --target lib/main.dart --no-tree-shake-icons"
    firebase_app_distribution(
    app: "1:116692744942:android:ca0c89e7acaa0ad37611ff",
    firebase_cli_token: "1//09mH2OKE4OcBkCgYIARAAGAkSNwF-L9Ir6LJbwvD0hy8ZOfLBUJOJCcBI5YGGcmcggTj8EBrHFiwHE9FqDJngzjU42zZfiFJEimU",
    android_artifact_type: "APK",
    android_artifact_path: "../build/app/outputs/apk/release/app-release.apk",
    testers: "mohammad.nashawi.55@gmail.com",
    release_notes: "First Fastlane Firebase Distribution",
    )
  end
end
